name: CD - Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # ЭТО ГЛАВНОЕ: запуск прямо на твоем сервере
    steps:
      - name: Deploy commands
        run: |
          # Входим в GHCR
          echo '${{ secrets.GHCR_TOKEN }}' | docker login ghcr.io -u '${{ secrets.GHCR_USER }}' --password-stdin
          # Переходим в папку с проектом
          cd ${{ secrets.DEPLOY_PATH }}
          # Обновляем и запускаем стек
          docker compose pull
          docker compose up -d
          docker image prune -f